### ISSUE TITLE
Cometary.Metaprogramming nuget package does not exist

### ISSUE THREAD

**Issue by maelmahdy** [71/Cometary#17]
When I run **Install-Package Cometary.Metaprogramming** command, it says: "unable to find package"

Am I missing something?

**Comment by 71** [comment]
It does exist, but in a pre-release. You can use `Install-Package -IncludePrerelease Cometary.Metaprogramming` instead.

**Comment by maelmahdy** [comment]
Yes, found it now, thank you!

**Comment by maelmahdy** [comment]
When a stable version will be available?

**Comment by 71** [comment]
It's not planned yet since I'm not certain it's stable in other programming environments. Is the pre-release tag bothering you?

**Comment by maelmahdy** [comment]
pre-release means that APIs may change so it's not solid yet.
For example, when I tried to implement the metaprogramming sample [described here](https://github.com/6A/Cometary/tree/master/src/Cometary.Metaprogramming), RegisterEdit method does not exist and I can't find its alternative.

**Comment by 71** [comment]
Well I don't think the library is solid, but since it's under 1.0 I don't mind removing the -pre tag. 

The project you linked is not a sample but the actual project. You can check the `test` directory for an actual sample. 

As for `RegisterEdit`, it's an extension method. I don't remember where exactly I defined it and can't check right now.
